export { Feedback } from './Feedback';
export { Maps } from './Maps';
export { Footer } from './Footer';
export { Questionnaire } from './Questionnaire';
export { Training } from './Training';
export { Portfolio } from './Portfolio';
export { Services } from './Services';
export { SecondarySlogan } from './SecondarySlogan'
export { Header } from './Header';
export { PrimarySlogan } from './PrimarySlogan';
export { About } from './About';
